ADMIN_ROLE = 'admin'
USER_ROLE = 'user'
MODERATOR_ROLE = 'moderator'

MAX_LENGTH_EMAIL = 254
MAX_LENGTH_USERNAME = 150
MAX_LENGTH_FIRST_LAST_NAME = 150

SUBJECT = 'Код подтверждения'
MESSAGE = 'Ваш код подтверждения: {}'
MAX_SCORE = 10
MIN_SCORE = 1
MAX_STR_LEN = 20
