# Generated by Django 3.2 on 2024-12-29 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsuser',
            name='username',
            field=models.CharField(help_text='Обязательное поле. Только буквы, цифры и @/./+/-/_.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Введите действительное имя пользователя. Это значение может содержать только буквы числа, и символы: @/./+/-/_ .', regex='^(?!me$)[\\w.@+-]+\\Z')], verbose_name='Имя пользователя'),
        ),
    ]
