# Generated by Django 3.2 on 2024-12-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20241224_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='raiting',
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
