# Generated by Django 3.2 on 2024-12-29 16:34

import django.core.validators
from django.db import migrations, models
import reviews.utils


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviewsuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='reviewsuser',
            name='username',
            field=models.CharField(help_text='Обязательное поле. Только буквы, цифры и @/./+/-/_.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Введите действительное имя пользователя. Это значение может содержать только буквы числа, и символы: @/./+/-/_ .', regex='^(?!me$)[\\w.@+-]+\\Z')], verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[reviews.utils.validate_current_year], verbose_name='Год выпуска'),
        ),
        migrations.DeleteModel(
            name='GenreTitle',
        ),
    ]
