# Generated by Django 3.2 on 2024-12-30 08:33

from django.db import migrations, models
import reviews.utils


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20241229_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Код подтверждения'),
        ),
        migrations.AlterField(
            model_name='reviewsuser',
            name='username',
            field=models.CharField(help_text='Обязательное поле. Только буквы, цифры и @/./+/-/_.', max_length=150, unique=True, validators=[reviews.utils.validate_username], verbose_name='Логин'),
        ),
    ]
