# Generated by Django 3.2 on 2024-12-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20241230_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsuser',
            name='confirmation_code',
            field=models.CharField(default='zzzzzz', max_length=6, verbose_name='Код подтверждения'),
        ),
    ]
